apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: traefik-letsencrypt-1
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: devops@stchome.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: traefik-letsencrypt-1
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: traefik  # Critical. The use of traefix-cert-manager failed issuing a cert.
